CREATE TABLE QUESTIONS_DB (
	QUESTION_ID INTEGER PRIMARY KEY,
	QUESTION VARCHAR(2048),
	OPTION_A VARCHAR(256),
	OPTION_B VARCHAR(256),
	OPTION_C VARCHAR(256),
	OPTION_D VARCHAR(256),
	CORRECT_ANSWER VARCHAR(1),
	TAG VARCHAR(256)
);

CREATE TABLE USER_DB (
	USER_ID INTEGER PRIMARY KEY,
	PASSWORD VARCHAR(128),
	NAME VARCHAR(128)
);

CREATE TABLE TEST_DB (
	USER_ID INTEGER,
	QUESTION_ID INTEGER,
	OPTION_SELECTED VARCHAR(1),
	TIME_TAKEN INTEGER,
	FLAGGED INTEGER,
	CONSTRAINT FK_1 FOREIGN KEY (USER_ID) REFERENCES USER_DB(USER_ID),
	CONSTRAINT FK_2 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS_DB(QUESTION_ID)
);
